import type { CasaId, RolId } from './roles'

export type Perfil = 'dulce' | 'citrico' | 'fuerte' | 'refrescante' | 'amargo' | 'frutal' | 'cremoso' | 'especiado'

export const PERFILES: { id: Perfil; nombre: string; descripcion: string }[] = [
  { id: 'dulce', nombre: 'Dulce', descripcion: 'azúcar al frente, poco filo' },
  { id: 'citrico', nombre: 'Cítrico', descripcion: 'limón, pomelo, naranja' },
  { id: 'fuerte', nombre: 'Fuerte', descripcion: 'se nota el destilado' },
  { id: 'refrescante', nombre: 'Refrescante', descripcion: 'largo, con hielo y burbuja' },
  { id: 'amargo', nombre: 'Amargo', descripcion: 'de aperitivo, seco' },
  { id: 'frutal', nombre: 'Frutal', descripcion: 'jugo de fruta de verdad' },
  { id: 'cremoso', nombre: 'Cremoso', descripcion: 'de postre, espeso' },
  { id: 'especiado', nombre: 'Especiado', descripcion: 'jengibre, hierbas, canela' },
]

export type Ingrediente = { rol: RolId; medida: string; nota?: string } | { casa: CasaId; medida: string; nota?: string }

export type Receta = {
  id: string
  nombre: string
  resumen: string
  perfiles: Perfil[]
  /** 1 suave, 2 medio, 3 fuerte. */
  intensidad: 1 | 2 | 3
  base: RolId | null
  sinAlcohol: boolean
  vaso: string
  minutos: number
  origen: string
  ingredientes: Ingrediente[]
  pasos: string[]
  tip: string
}

export const RECETAS: Receta[] = [
  {
    id: 'pisco-sour',
    nombre: 'Pisco sour',
    resumen: 'El ácido que todos saben tomar. Limón de Pica si lo encuentras.',
    perfiles: ['citrico', 'fuerte'],
    intensidad: 3,
    base: 'pisco',
    sinAlcohol: false,
    vaso: 'Copa baja fría',
    minutos: 5,
    origen: 'Chile',
    ingredientes: [
      { rol: 'pisco', medida: '60 ml de pisco 35°' },
      { casa: 'limon', medida: '30 ml de jugo recién exprimido' },
      { rol: 'jarabe-goma', medida: '20 ml de jarabe de goma' },
      { casa: 'hielo', medida: '1 taza' },
    ],
    pasos: [
      'Exprime el limón al momento. El envasado deja un dejo metálico.',
      'Junta pisco, limón y jarabe con el hielo en la coctelera o la juguera.',
      'Bate 15 segundos hasta que el vaso se escarche por fuera.',
      'Cuela sobre la copa fría y déjalo reposar medio minuto antes de servir.',
    ],
    tip: 'Si queda muy ácido, sube el jarabe de a 5 ml. Nunca al revés.',
  },
  {
    id: 'piscola',
    nombre: 'Piscola',
    resumen: 'Dos ingredientes y cero ciencia. La medida es lo único que importa.',
    perfiles: ['dulce', 'fuerte'],
    intensidad: 3,
    base: 'pisco',
    sinAlcohol: false,
    vaso: 'Vaso largo',
    minutos: 2,
    origen: 'Chile',
    ingredientes: [
      { rol: 'pisco', medida: '70 ml de pisco' },
      { rol: 'cola', medida: '150 ml de bebida cola bien fría' },
      { casa: 'hielo', medida: '4 cubos' },
    ],
    pasos: [
      'Llena el vaso con hielo hasta arriba. Menos hielo derrite más rápido.',
      'Sirve el pisco primero para que la bebida lo mezcle sola.',
      'Completa con la cola inclinando el vaso, sin revolver.',
    ],
    tip: 'Una rodaja de limón cambia la piscola entera. Pruébalo una vez.',
  },
  {
    id: 'gin-tonic',
    nombre: 'Gin tonic botánico',
    resumen: 'Amargo, seco y largo. El trago de la tarde que no cansa.',
    perfiles: ['amargo', 'refrescante', 'citrico'],
    intensidad: 2,
    base: 'gin',
    sinAlcohol: false,
    vaso: 'Copa balón',
    minutos: 3,
    origen: 'Inglaterra',
    ingredientes: [
      { rol: 'gin', medida: '50 ml de gin' },
      { rol: 'tonica', medida: '150 ml de tónica fría' },
      { casa: 'limon', medida: '2 rodajas' },
      { casa: 'hielo', medida: 'copa llena' },
    ],
    pasos: [
      'Enfría la copa con hielo y bota el agua que suelte.',
      'Sirve el gin sobre el hielo nuevo.',
      'Vierte la tónica por el dorso de una cuchara para no matar el gas.',
      'Estruja la cáscara de limón sobre la copa y déjala caer dentro.',
    ],
    tip: 'Tónica chica y fría. La de litro y medio abierta pierde gas en veinte minutos.',
  },
  {
    id: 'negroni',
    nombre: 'Negroni',
    resumen: 'Partes iguales, sin jugo, sin azúcar. Amargo de verdad.',
    perfiles: ['amargo', 'fuerte'],
    intensidad: 3,
    base: 'gin',
    sinAlcohol: false,
    vaso: 'Vaso bajo',
    minutos: 3,
    origen: 'Italia',
    ingredientes: [
      { rol: 'gin', medida: '30 ml' },
      { rol: 'campari', medida: '30 ml' },
      { rol: 'vermut-rojo', medida: '30 ml' },
      { casa: 'naranja', medida: '1 cáscara' },
      { casa: 'hielo', medida: '1 cubo grande' },
    ],
    pasos: [
      'Pon un cubo grande en el vaso bajo. Mientras menos superficie, menos agua.',
      'Sirve los tres licores directo sobre el hielo.',
      'Revuelve 20 segundos con cuchara larga.',
      'Estruja la cáscara de naranja encima y bórdala en el vaso.',
    ],
    tip: 'Si nunca has tomado amargo, parte con 20 ml de Campari en vez de 30.',
  },
  {
    id: 'aperol-spritz',
    nombre: 'Aperol spritz',
    resumen: 'Naranja, burbuja y poca graduación. Aguanta una tarde entera de calor.',
    perfiles: ['amargo', 'refrescante', 'citrico'],
    intensidad: 1,
    base: 'aperol',
    sinAlcohol: false,
    vaso: 'Copa de vino',
    minutos: 3,
    origen: 'Italia',
    ingredientes: [
      { rol: 'aperol', medida: '60 ml' },
      { rol: 'espumante', medida: '90 ml' },
      { rol: 'agua-con-gas', medida: 'un chorro' },
      { casa: 'naranja', medida: '1 rodaja' },
      { casa: 'hielo', medida: 'copa llena' },
    ],
    pasos: [
      'Llena la copa de hielo hasta el borde.',
      'Sirve el espumante primero, después el Aperol.',
      'Corona con el agua con gas y la rodaja de naranja.',
    ],
    tip: 'El orden importa: si pones el Aperol primero, el espumante se aplana.',
  },
  {
    id: 'moscow-mule',
    nombre: 'Moscow mule',
    resumen: 'Jengibre y limón sobre vodka. Pica y refresca al mismo tiempo.',
    perfiles: ['especiado', 'refrescante', 'citrico'],
    intensidad: 2,
    base: 'vodka',
    sinAlcohol: false,
    vaso: 'Jarro de cobre o vaso largo',
    minutos: 3,
    origen: 'Estados Unidos',
    ingredientes: [
      { rol: 'vodka', medida: '50 ml' },
      { rol: 'ginger-beer', medida: '150 ml' },
      { casa: 'limon', medida: '15 ml de jugo' },
      { casa: 'hielo', medida: 'vaso lleno' },
    ],
    pasos: [
      'Exprime el limón directo en el vaso.',
      'Agrega el vodka y llena de hielo.',
      'Completa con ginger beer y revuelve una sola vez.',
    ],
    tip: 'Con ginger ale queda más dulce y menos picante. Es otra cosa, pero funciona.',
  },
  {
    id: 'mojito',
    nombre: 'Mojito',
    resumen: 'Menta, limón y ron blanco. El error clásico es machacar de más.',
    perfiles: ['refrescante', 'citrico', 'dulce'],
    intensidad: 2,
    base: 'ron-blanco',
    sinAlcohol: false,
    vaso: 'Vaso largo',
    minutos: 5,
    origen: 'Cuba',
    ingredientes: [
      { rol: 'ron-blanco', medida: '50 ml' },
      { casa: 'menta', medida: '10 hojas' },
      { casa: 'limon', medida: '25 ml de jugo' },
      { casa: 'azucar', medida: '2 cucharaditas' },
      { rol: 'agua-con-gas', medida: '100 ml' },
      { casa: 'hielo', medida: 'hielo molido' },
    ],
    pasos: [
      'Aprieta la menta contra la palma de la mano y suéltala en el vaso. No la muelas.',
      'Suma azúcar y jugo de limón, revuelve hasta disolver.',
      'Agrega el ron, llena de hielo molido y completa con agua con gas.',
    ],
    tip: 'La menta machacada suelta clorofila y amarga el trago entero.',
  },
  {
    id: 'cuba-libre',
    nombre: 'Cuba libre',
    resumen: 'Ron con cola y harto limón. Simple y directo.',
    perfiles: ['dulce', 'citrico'],
    intensidad: 2,
    base: 'ron-anejo',
    sinAlcohol: false,
    vaso: 'Vaso largo',
    minutos: 2,
    origen: 'Cuba',
    ingredientes: [
      { rol: 'ron-anejo', medida: '50 ml' },
      { rol: 'cola', medida: '150 ml' },
      { casa: 'limon', medida: '2 gajos' },
      { casa: 'hielo', medida: 'vaso lleno' },
    ],
    pasos: [
      'Exprime los gajos de limón dentro del vaso y déjalos caer.',
      'Llena de hielo y sirve el ron.',
      'Completa con la cola sin revolver.',
    ],
    tip: 'El ron añejo aporta madera. Con ron blanco queda más plano.',
  },
  {
    id: 'daiquiri',
    nombre: 'Daiquiri',
    resumen: 'Tres ingredientes en equilibrio exacto. No perdona medidas al ojo.',
    perfiles: ['citrico', 'fuerte'],
    intensidad: 3,
    base: 'ron-blanco',
    sinAlcohol: false,
    vaso: 'Copa coctelera fría',
    minutos: 4,
    origen: 'Cuba',
    ingredientes: [
      { rol: 'ron-blanco', medida: '60 ml' },
      { casa: 'limon', medida: '25 ml de jugo' },
      { rol: 'jarabe-goma', medida: '20 ml' },
      { casa: 'hielo', medida: '1 taza' },
    ],
    pasos: [
      'Enfría la copa en el congelador mientras preparas el resto.',
      'Bate los tres ingredientes con hielo 12 segundos.',
      'Cuela doble para que no pasen astillas de hielo.',
    ],
    tip: 'Si el ron es más suave que 40°, baja el jarabe a 15 ml.',
  },
  {
    id: 'pina-colada',
    nombre: 'Piña colada',
    resumen: 'Postre en vaso. Dulce sin disimulo.',
    perfiles: ['dulce', 'cremoso', 'frutal'],
    intensidad: 1,
    base: 'ron-blanco',
    sinAlcohol: false,
    vaso: 'Vaso alto',
    minutos: 4,
    origen: 'Puerto Rico',
    ingredientes: [
      { rol: 'ron-blanco', medida: '50 ml' },
      { rol: 'licor-coco', medida: '30 ml' },
      { rol: 'jugo-pina', medida: '120 ml' },
      { casa: 'hielo', medida: '1 taza' },
    ],
    pasos: [
      'Licúa todo con el hielo hasta que quede sin grumos.',
      'Sirve en vaso alto, sin colar.',
      'Corona con un trozo de piña si tienes.',
    ],
    tip: 'Congela el jugo de piña en cubetera y usa eso como hielo. No se aguacha.',
  },
  {
    id: 'margarita',
    nombre: 'Margarita',
    resumen: 'Tequila, limón y sal en el borde. Corto y filoso.',
    perfiles: ['citrico', 'fuerte'],
    intensidad: 3,
    base: 'tequila',
    sinAlcohol: false,
    vaso: 'Copa con borde salado',
    minutos: 4,
    origen: 'México',
    ingredientes: [
      { rol: 'tequila', medida: '50 ml' },
      { rol: 'triple-sec', medida: '25 ml' },
      { casa: 'limon', medida: '25 ml de jugo' },
      { casa: 'sal', medida: 'para el borde' },
      { casa: 'hielo', medida: '1 taza' },
    ],
    pasos: [
      'Pasa un gajo de limón por el borde de la copa y apóyala sobre sal gruesa.',
      'Bate tequila, triple sec y limón con hielo 12 segundos.',
      'Cuela dentro de la copa cuidando no botar la sal.',
    ],
    tip: 'Sal solo en la mitad del borde. Así cada quien elige de qué lado toma.',
  },
  {
    id: 'paloma',
    nombre: 'Paloma',
    resumen: 'Pomelo y tequila. Más fácil de tomar que la margarita.',
    perfiles: ['citrico', 'refrescante'],
    intensidad: 2,
    base: 'tequila',
    sinAlcohol: false,
    vaso: 'Vaso largo',
    minutos: 3,
    origen: 'México',
    ingredientes: [
      { rol: 'tequila', medida: '50 ml' },
      { rol: 'pomelo', medida: '150 ml' },
      { casa: 'limon', medida: '15 ml de jugo' },
      { casa: 'sal', medida: 'una pizca dentro' },
      { casa: 'hielo', medida: 'vaso lleno' },
    ],
    pasos: [
      'Sirve el tequila sobre hielo.',
      'Suma el jugo de limón y la pizca de sal.',
      'Completa con bebida de pomelo bien fría.',
    ],
    tip: 'La sal adentro, no en el borde: levanta el pomelo y baja el amargo.',
  },
  {
    id: 'whisky-sour',
    nombre: 'Whisky sour',
    resumen: 'La versión con madera del sour. Menos ácido, más redondo.',
    perfiles: ['citrico', 'fuerte'],
    intensidad: 3,
    base: 'whisky',
    sinAlcohol: false,
    vaso: 'Vaso bajo',
    minutos: 4,
    origen: 'Estados Unidos',
    ingredientes: [
      { rol: 'whisky', medida: '50 ml' },
      { casa: 'limon', medida: '25 ml de jugo' },
      { rol: 'jarabe-goma', medida: '20 ml' },
      { casa: 'hielo', medida: '1 taza' },
    ],
    pasos: [
      'Bate whisky, limón y jarabe con hielo hasta enfriar la coctelera.',
      'Cuela sobre un vaso bajo con un cubo grande.',
      'Termina con una cáscara de limón.',
    ],
    tip: 'Con whisky escocés queda ahumado; con bourbon, dulce. Elige según el ánimo.',
  },
  {
    id: 'vodka-energetica',
    nombre: 'Vodka con energética',
    resumen: 'El trago de la previa. Frío, dulce y con cafeína.',
    perfiles: ['dulce', 'fuerte'],
    intensidad: 3,
    base: 'vodka',
    sinAlcohol: false,
    vaso: 'Vaso largo',
    minutos: 2,
    origen: 'Chile',
    ingredientes: [
      { rol: 'vodka', medida: '50 ml' },
      { rol: 'energetica', medida: '120 ml' },
      { casa: 'limon', medida: '1 rodaja' },
      { casa: 'hielo', medida: 'vaso lleno' },
    ],
    pasos: [
      'Llena el vaso de hielo y sirve el vodka.',
      'Completa con la energética bien fría.',
      'Rodaja de limón al borde.',
    ],
    tip: 'Mezclar alcohol con cafeína esconde los efectos. Toma agua entre vaso y vaso.',
  },
  {
    id: 'amanecer-santiaguino',
    nombre: 'Amanecer santiaguino',
    resumen: 'Naranja y frutilla en capas sobre tequila. Se toma con los ojos primero.',
    perfiles: ['frutal', 'dulce'],
    intensidad: 2,
    base: 'tequila',
    sinAlcohol: false,
    vaso: 'Vaso alto',
    minutos: 4,
    origen: 'Santiago',
    ingredientes: [
      { rol: 'tequila', medida: '50 ml' },
      { rol: 'jugo-naranja', medida: '120 ml' },
      { rol: 'jugo-frutilla', medida: '30 ml, al final' },
      { casa: 'hielo', medida: 'vaso lleno' },
    ],
    pasos: [
      'Vaso lleno de hielo, tequila y jugo de naranja. Revuelve.',
      'Vierte el néctar de frutilla muy despacio por el borde.',
      'No revuelvas: la capa roja debe quedar abajo.',
    ],
    tip: 'Mientras más frío el jugo, más limpia queda la separación de colores.',
  },
  {
    id: 'terremoto',
    nombre: 'Terremoto',
    resumen: 'Vino dulce con helado de piña. Entra fácil y pega tarde.',
    perfiles: ['dulce', 'frutal'],
    intensidad: 3,
    base: 'vino-dulce',
    sinAlcohol: false,
    vaso: 'Vaso de pinta',
    minutos: 3,
    origen: 'Chile',
    ingredientes: [
      { rol: 'vino-dulce', medida: '300 ml de vino blanco dulce' },
      { casa: 'helado', medida: '2 bolas' },
      { rol: 'fernet', medida: 'un chorrito, opcional' },
    ],
    pasos: [
      'Sirve el vino dulce bien frío hasta tres cuartos del vaso.',
      'Deja caer las bolas de helado de piña encima.',
      'Si te gusta más seco, corona con un chorro de fernet.',
    ],
    tip: 'La réplica es medio vaso. La segunda réplica ya es problema tuyo.',
  },
  {
    id: 'jote',
    nombre: 'Jote',
    resumen: 'Vino tinto con bebida cola. Barato, honesto y muy chileno.',
    perfiles: ['dulce', 'refrescante'],
    intensidad: 2,
    base: 'vino-tinto',
    sinAlcohol: false,
    vaso: 'Vaso largo',
    minutos: 2,
    origen: 'Chile',
    ingredientes: [
      { rol: 'vino-tinto', medida: '150 ml' },
      { rol: 'cola', medida: '150 ml' },
      { casa: 'hielo', medida: 'vaso lleno' },
      { casa: 'limon', medida: '1 rodaja' },
    ],
    pasos: [
      'Mitad y mitad sobre hielo.',
      'Revuelve una vez y agrega la rodaja de limón.',
    ],
    tip: 'Usa un tinto joven y frutoso. Un cabernet con crianza se pelea con la cola.',
  },
  {
    id: 'fernet-cola',
    nombre: 'Fernet con cola',
    resumen: 'Herbal y amargo. O te gusta al primer sorbo o nunca.',
    perfiles: ['amargo', 'especiado'],
    intensidad: 3,
    base: 'fernet',
    sinAlcohol: false,
    vaso: 'Vaso largo',
    minutos: 2,
    origen: 'Argentina',
    ingredientes: [
      { rol: 'fernet', medida: '50 ml' },
      { rol: 'cola', medida: '150 ml' },
      { casa: 'hielo', medida: 'vaso lleno' },
    ],
    pasos: [
      'Hielo hasta arriba, fernet encima.',
      'Completa con la cola de a poco: hace mucha espuma.',
    ],
    tip: 'Un tercio de fernet y dos de cola es la proporción de arranque.',
  },
  {
    id: 'michelada',
    nombre: 'Michelada',
    resumen: 'Cerveza con limón, sal y merkén. Para el calor del mediodía.',
    perfiles: ['citrico', 'refrescante', 'especiado'],
    intensidad: 1,
    base: 'cerveza',
    sinAlcohol: false,
    vaso: 'Vaso escarchado',
    minutos: 3,
    origen: 'México',
    ingredientes: [
      { rol: 'cerveza', medida: '1 lata bien fría' },
      { casa: 'limon', medida: '20 ml de jugo' },
      { casa: 'sal', medida: 'para el borde' },
      { casa: 'merken', medida: 'una pizca' },
      { casa: 'hielo', medida: '3 cubos' },
    ],
    pasos: [
      'Escarcha el borde con limón, sal y merkén.',
      'Pon el jugo de limón y el hielo en el vaso.',
      'Sirve la cerveza inclinando el vaso para no perder toda la espuma.',
    ],
    tip: 'Una lager suave rinde mejor que una cerveza con carácter propio.',
  },
  {
    id: 'espresso-martini',
    nombre: 'Espresso martini',
    resumen: 'Café, vodka y licor de café. El trago de la sobremesa larga.',
    perfiles: ['cremoso', 'fuerte'],
    intensidad: 3,
    base: 'vodka',
    sinAlcohol: false,
    vaso: 'Copa coctelera',
    minutos: 5,
    origen: 'Inglaterra',
    ingredientes: [
      { rol: 'vodka', medida: '50 ml' },
      { rol: 'licor-cafe', medida: '25 ml' },
      { casa: 'cafe', medida: '30 ml de espresso caliente' },
      { casa: 'hielo', medida: '1 taza' },
    ],
    pasos: [
      'Prepara el espresso recién hecho: la espuma sale de ahí.',
      'Bate fuerte los tres líquidos con hielo, 15 segundos.',
      'Cuela y sirve rápido, antes de que baje la espuma.',
    ],
    tip: 'Café frío no arma espuma. Tiene que ir caliente a la coctelera.',
  },
  {
    id: 'jager-bomba',
    nombre: 'Jäger bomba',
    resumen: 'Shot dentro del vaso. Se toma de una y no se piensa mucho.',
    perfiles: ['dulce', 'fuerte', 'especiado'],
    intensidad: 3,
    base: 'jagermeister',
    sinAlcohol: false,
    vaso: 'Vaso bajo más shot',
    minutos: 1,
    origen: 'Alemania',
    ingredientes: [
      { rol: 'jagermeister', medida: '40 ml en el shot' },
      { rol: 'energetica', medida: '120 ml en el vaso' },
    ],
    pasos: [
      'Sirve la energética fría en el vaso bajo, hasta la mitad.',
      'Llena el shot con Jägermeister del refrigerador.',
      'Deja caer el shot dentro del vaso y tómalo al tiro.',
    ],
    tip: 'El Jägermeister se guarda en el congelador. A temperatura ambiente es otra cosa.',
  },
  {
    id: 'baileys-hielo',
    nombre: 'Crema irlandesa en las rocas',
    resumen: 'Dos ingredientes y ninguno es limón. El cierre de la noche.',
    perfiles: ['cremoso', 'dulce'],
    intensidad: 1,
    base: 'crema-irlandesa',
    sinAlcohol: false,
    vaso: 'Vaso bajo',
    minutos: 1,
    origen: 'Irlanda',
    ingredientes: [
      { rol: 'crema-irlandesa', medida: '60 ml' },
      { casa: 'hielo', medida: '2 cubos grandes' },
      { casa: 'canela', medida: 'un toque encima' },
    ],
    pasos: [
      'Dos cubos grandes en el vaso.',
      'Sirve la crema encima y espolvorea canela.',
    ],
    tip: 'Cubos grandes: los chicos la diluyen y la dejan aguada en dos minutos.',
  },
  {
    id: 'sour-de-mango',
    nombre: 'Sour de mango al paso',
    resumen: 'Sour listo del catálogo, arreglado con limón fresco.',
    perfiles: ['frutal', 'citrico', 'dulce'],
    intensidad: 2,
    base: 'sour-listo',
    sinAlcohol: false,
    vaso: 'Copa baja',
    minutos: 2,
    origen: 'Chile',
    ingredientes: [
      { rol: 'sour-listo', medida: '120 ml' },
      { casa: 'limon', medida: '10 ml de jugo' },
      { casa: 'hielo', medida: '1 taza' },
    ],
    pasos: [
      'Bate el sour listo con hielo para airearlo.',
      'Agrega el limón fresco: le devuelve el filo que el envasado pierde.',
      'Cuela en copa baja.',
    ],
    tip: 'Sirve para cuando llegan visitas sin aviso y no hay tiempo de exprimir.',
  },
  {
    id: 'limonada-jengibre',
    nombre: 'Limonada de jengibre',
    resumen: 'Sin alcohol y con carácter. No es un jugo con hielo.',
    perfiles: ['citrico', 'refrescante', 'especiado'],
    intensidad: 1,
    base: null,
    sinAlcohol: true,
    vaso: 'Vaso largo',
    minutos: 3,
    origen: 'Chile',
    ingredientes: [
      { rol: 'ginger-ale', medida: '150 ml' },
      { casa: 'limon', medida: '30 ml de jugo' },
      { casa: 'jengibre', medida: '3 rodajas finas' },
      { casa: 'menta', medida: '5 hojas' },
      { casa: 'hielo', medida: 'vaso lleno' },
    ],
    pasos: [
      'Aprieta las rodajas de jengibre en el fondo del vaso con la cuchara.',
      'Suma el jugo de limón, la menta y el hielo.',
      'Completa con ginger ale.',
    ],
    tip: 'Deja el jengibre 10 minutos en el jugo de limón antes de armar el vaso.',
  },
  {
    id: 'pina-sin-alcohol',
    nombre: 'Piña colada sin alcohol',
    resumen: 'Misma textura, sin ron. Para quien maneja o no toma.',
    perfiles: ['dulce', 'cremoso', 'frutal'],
    intensidad: 1,
    base: null,
    sinAlcohol: true,
    vaso: 'Vaso alto',
    minutos: 4,
    origen: 'Puerto Rico',
    ingredientes: [
      { rol: 'jugo-pina', medida: '180 ml' },
      { rol: 'jugo-mango', medida: '60 ml' },
      { casa: 'hielo', medida: '1 taza' },
    ],
    pasos: [
      'Licúa los jugos con el hielo hasta que quede espeso.',
      'Sirve sin colar.',
    ],
    tip: 'Una cucharada de leche condensada la deja idéntica a la versión con ron.',
  },
  {
    id: 'tonica-pomelo',
    nombre: 'Tónica de pomelo',
    resumen: 'Amargo sin alcohol. Aperitivo de verdad para el que no toma.',
    perfiles: ['amargo', 'citrico', 'refrescante'],
    intensidad: 1,
    base: null,
    sinAlcohol: true,
    vaso: 'Copa balón',
    minutos: 2,
    origen: 'Italia',
    ingredientes: [
      { rol: 'tonica', medida: '150 ml' },
      { rol: 'pomelo', medida: '80 ml' },
      { casa: 'naranja', medida: '1 rodaja' },
      { casa: 'hielo', medida: 'copa llena' },
    ],
    pasos: [
      'Copa llena de hielo.',
      'Mitad tónica, mitad bebida de pomelo.',
      'Rodaja de naranja estrujada encima.',
    ],
    tip: 'Sirve la misma copa que el gin tonic: nadie nota quién está tomando qué.',
  },
  {
    id: 'destornillador',
    nombre: 'Destornillador',
    resumen: 'Vodka con jugo de naranja. El más simple de todos y por eso nunca falla.',
    perfiles: ['frutal', 'refrescante', 'dulce'],
    intensidad: 2,
    base: 'vodka',
    sinAlcohol: false,
    vaso: 'Vaso largo',
    minutos: 2,
    origen: 'Estados Unidos',
    ingredientes: [
      { rol: 'vodka', medida: '50 ml' },
      { rol: 'jugo-naranja', medida: '150 ml' },
      { casa: 'hielo', medida: 'vaso lleno' },
    ],
    pasos: [
      'Llena el vaso de hielo y sirve el vodka.',
      'Completa con el jugo de naranja bien frío.',
      'Revuelve una sola vez con una cuchara larga.',
    ],
    tip: 'Jugo recién exprimido cambia el trago entero, pero el envasado también funciona bien frío.',
  },
  {
    id: 'amaretto-sour',
    nombre: 'Amaretto sour',
    resumen: 'Almendra y limón. El sour más dulce de la carta.',
    perfiles: ['dulce', 'citrico'],
    intensidad: 2,
    base: 'amaretto',
    sinAlcohol: false,
    vaso: 'Vaso bajo',
    minutos: 4,
    origen: 'Italia',
    ingredientes: [
      { rol: 'amaretto', medida: '60 ml' },
      { casa: 'limon', medida: '25 ml de jugo' },
      { rol: 'jarabe-goma', medida: '10 ml' },
      { casa: 'hielo', medida: '1 taza' },
    ],
    pasos: [
      'Bate el amaretto, el limón y el jarabe con hielo 12 segundos.',
      'Cuela sobre un vaso bajo con un cubo grande.',
      'Termina con una cáscara de limón si quieres.',
    ],
    tip: 'El amaretto ya es dulce: prueba antes de sumar todo el jarabe, capaz que sobra.',
  },
  {
    id: 'soju-limon-soda',
    nombre: 'Soju con limón soda',
    resumen: 'El mix casual coreano. Bajo, dulce y fácil de tomar en grupo.',
    perfiles: ['dulce', 'refrescante'],
    intensidad: 1,
    base: 'soju',
    sinAlcohol: false,
    vaso: 'Vaso largo',
    minutos: 2,
    origen: 'Corea del Sur',
    ingredientes: [
      { rol: 'soju', medida: '60 ml' },
      { rol: 'lima-limon', medida: '120 ml de bebida lima limón' },
      { casa: 'limon', medida: '1 rodaja' },
      { casa: 'hielo', medida: 'vaso lleno' },
    ],
    pasos: [
      'Llena el vaso de hielo y sirve el soju.',
      'Completa con la bebida lima limón bien fría.',
      'Rodaja de limón al borde y una sola revuelta.',
    ],
    tip: 'El soju rinde para varias rondas: una botella de 360 ml da para tres o cuatro vasos.',
  },
  {
    id: 'bellini',
    nombre: 'Bellini',
    resumen: 'Espumante con durazno. Corto, frío y de aperitivo.',
    perfiles: ['frutal', 'dulce', 'refrescante'],
    intensidad: 1,
    base: 'espumante',
    sinAlcohol: false,
    vaso: 'Copa de champán',
    minutos: 2,
    origen: 'Italia',
    ingredientes: [
      { rol: 'espumante', medida: '100 ml bien frío' },
      { rol: 'jugo-durazno', medida: '50 ml de néctar de durazno' },
    ],
    pasos: [
      'Vierte el néctar de durazno frío en el fondo de la copa.',
      'Completa con el espumante muy despacio, por el borde, para no perder gas.',
      'Revuelve una sola vez con una cuchara larga.',
    ],
    tip: 'Sin hielo: la copa y los ingredientes tienen que estar fríos de antes.',
  },
  {
    id: 'blanco-de-verano',
    nombre: 'Blanco de verano',
    resumen: 'Vino blanco con soda de lima limón. La versión ligera del tinto de verano.',
    perfiles: ['refrescante', 'citrico', 'dulce'],
    intensidad: 1,
    base: 'vino-blanco',
    sinAlcohol: false,
    vaso: 'Vaso largo',
    minutos: 2,
    origen: 'España',
    ingredientes: [
      { rol: 'vino-blanco', medida: '100 ml' },
      { rol: 'lima-limon', medida: '100 ml de bebida lima limón' },
      { casa: 'limon', medida: '1 rodaja' },
      { casa: 'hielo', medida: 'vaso lleno' },
    ],
    pasos: [
      'Llena el vaso de hielo y sirve el vino bien frío.',
      'Completa con la bebida lima limón.',
      'Rodaja de limón al borde.',
    ],
    tip: 'Un vino blanco joven y frutoso rinde mejor acá que uno con crianza en madera.',
  },
  {
    id: 'sangria',
    nombre: 'Sangría',
    resumen: 'Vino tinto con fruta y un toque de burbuja. Para compartir, nunca para uno solo.',
    perfiles: ['frutal', 'dulce', 'refrescante'],
    intensidad: 1,
    base: 'vino-tinto',
    sinAlcohol: false,
    vaso: 'Jarra o vaso de pinta',
    minutos: 5,
    origen: 'España',
    ingredientes: [
      { rol: 'vino-tinto', medida: '200 ml' },
      { rol: 'jugo-naranja', medida: '50 ml' },
      { casa: 'naranja', medida: '3 rodajas' },
      { rol: 'espumante', medida: 'un chorro para el final' },
      { casa: 'hielo', medida: 'jarra llena' },
    ],
    pasos: [
      'Sirve el vino tinto sobre hielo en la jarra.',
      'Suma el jugo de naranja y las rodajas de fruta.',
      'Corona con un chorro de espumante justo antes de servir.',
    ],
    tip: 'Déjala reposar 15 minutos con la fruta adentro antes de tomarla: ahí agarra sabor.',
  },
  {
    id: 'caipiroska',
    nombre: 'Caipiroska',
    resumen: 'La caipirinha hecha con vodka. Limón machacado, sin filtro.',
    perfiles: ['citrico', 'fuerte'],
    intensidad: 3,
    base: 'vodka',
    sinAlcohol: false,
    vaso: 'Vaso bajo',
    minutos: 4,
    origen: 'Brasil',
    ingredientes: [
      { rol: 'vodka', medida: '60 ml' },
      { casa: 'limon', medida: '1 limón entero, en trozos' },
      { casa: 'azucar', medida: '2 cucharaditas' },
      { casa: 'hielo', medida: 'vaso lleno, molido' },
    ],
    pasos: [
      'Corta el limón en cuartos y machácalo con el azúcar directo en el vaso.',
      'Suma el vodka y revuelve hasta disolver el azúcar.',
      'Llena con hielo molido.',
    ],
    tip: 'Machaca solo la pulpa, no la cáscara blanca: esa parte amarga el trago.',
  },
  {
    id: 'campari-spritz',
    nombre: 'Campari spritz',
    resumen: 'Más amargo y menos dulce que el de Aperol. Para el que ya toma amargo seguido.',
    perfiles: ['amargo', 'refrescante'],
    intensidad: 2,
    base: 'campari',
    sinAlcohol: false,
    vaso: 'Copa de vino',
    minutos: 3,
    origen: 'Italia',
    ingredientes: [
      { rol: 'campari', medida: '60 ml' },
      { rol: 'espumante', medida: '90 ml' },
      { rol: 'agua-con-gas', medida: 'un chorro' },
      { casa: 'naranja', medida: '1 rodaja' },
      { casa: 'hielo', medida: 'copa llena' },
    ],
    pasos: [
      'Llena la copa de hielo.',
      'Sirve el espumante primero, después el Campari.',
      'Corona con el agua con gas y la rodaja de naranja.',
    ],
    tip: 'Si el amargo se siente muy fuerte, sube un poco el espumante en vez de bajar el Campari.',
  },
  {
    id: 'irish-coffee',
    nombre: 'Irish coffee',
    resumen: 'Café caliente con whisky. El cierre perfecto de una cena larga.',
    perfiles: ['cremoso', 'fuerte'],
    intensidad: 2,
    base: 'whisky',
    sinAlcohol: false,
    vaso: 'Vaso de vidrio con asa',
    minutos: 5,
    origen: 'Irlanda',
    ingredientes: [
      { rol: 'whisky', medida: '40 ml' },
      { casa: 'cafe', medida: '120 ml de café caliente recién hecho' },
      { casa: 'azucar', medida: '1 cucharadita' },
    ],
    pasos: [
      'Disuelve el azúcar en el café caliente.',
      'Suma el whisky y revuelve.',
      'Sirve en un vaso resistente al calor.',
    ],
    tip: 'Si tienes crema, viértela fría por el dorso de una cuchara al final: queda flotando arriba.',
  },
  {
    id: 'vermut-tonica',
    nombre: 'Vermut con tónica',
    resumen: 'El aperitivo español de sobremesa. Corto, dulzón y con burbuja.',
    perfiles: ['dulce', 'amargo', 'refrescante'],
    intensidad: 1,
    base: 'vermut-rojo',
    sinAlcohol: false,
    vaso: 'Copa balón',
    minutos: 2,
    origen: 'España',
    ingredientes: [
      { rol: 'vermut-rojo', medida: '60 ml' },
      { rol: 'tonica', medida: '90 ml' },
      { casa: 'naranja', medida: '1 rodaja' },
      { casa: 'hielo', medida: 'copa llena' },
    ],
    pasos: [
      'Copa llena de hielo, sirve el vermut.',
      'Completa con la tónica, despacio.',
      'Rodaja de naranja al final.',
    ],
    tip: 'Va bien antes de comer, no después: abre el apetito en vez de cerrarlo.',
  },
  {
    id: 'tom-collins',
    nombre: 'Tom Collins',
    resumen: 'Gin con limón, azúcar y soda. El antecesor directo del gin tonic.',
    perfiles: ['citrico', 'refrescante'],
    intensidad: 2,
    base: 'gin',
    sinAlcohol: false,
    vaso: 'Vaso largo (vaso Collins)',
    minutos: 4,
    origen: 'Inglaterra',
    ingredientes: [
      { rol: 'gin', medida: '50 ml' },
      { casa: 'limon', medida: '25 ml de jugo' },
      { casa: 'azucar', medida: '2 cucharaditas' },
      { rol: 'agua-con-gas', medida: '100 ml' },
      { casa: 'hielo', medida: 'vaso lleno' },
    ],
    pasos: [
      'Disuelve el azúcar en el jugo de limón dentro del vaso.',
      'Suma el gin y llena de hielo.',
      'Completa con agua con gas y revuelve una vez.',
    ],
    tip: 'Con tónica en vez de soda, este mismo trago se transforma en un gin tonic.',
  },
  {
    id: 'old-fashioned',
    nombre: 'Old fashioned',
    resumen: 'Whisky, azúcar y cáscara de naranja. El cóctel más antiguo que sigue vivo.',
    perfiles: ['fuerte', 'dulce'],
    intensidad: 3,
    base: 'whisky',
    sinAlcohol: false,
    vaso: 'Vaso bajo',
    minutos: 4,
    origen: 'Estados Unidos',
    ingredientes: [
      { rol: 'whisky', medida: '60 ml' },
      { casa: 'azucar', medida: '1 cucharadita' },
      { casa: 'naranja', medida: '1 cáscara' },
      { casa: 'hielo', medida: '1 cubo grande' },
    ],
    pasos: [
      'Humedece el azúcar con un par de gotas de agua y disuélvela en el fondo del vaso.',
      'Agrega el whisky y el cubo de hielo grande.',
      'Estruja la cáscara de naranja sobre el vaso y déjala caer dentro.',
    ],
    tip: 'La receta original lleva unas gotas de angostura; sin ella igual funciona, solo queda menos especiado.',
  },
  {
    id: 'french-75',
    nombre: 'French 75',
    resumen: 'Gin con burbuja. El cóctel de brindis para el que no quiere solo espumante.',
    perfiles: ['citrico', 'refrescante', 'dulce'],
    intensidad: 2,
    base: 'gin',
    sinAlcohol: false,
    vaso: 'Copa de champán',
    minutos: 4,
    origen: 'Francia',
    ingredientes: [
      { rol: 'gin', medida: '40 ml' },
      { casa: 'limon', medida: '15 ml de jugo' },
      { rol: 'jarabe-goma', medida: '10 ml' },
      { rol: 'espumante', medida: '90 ml, para completar' },
    ],
    pasos: [
      'Bate el gin, el limón y el jarabe con hielo 10 segundos.',
      'Cuela dentro de la copa.',
      'Completa con el espumante bien frío, despacio.',
    ],
    tip: 'Si lo quieres más corto, baja el espumante a 60 ml y sube un poco el gin.',
  },
  {
    id: 'mimosa',
    nombre: 'Mimosa',
    resumen: 'Espumante con jugo de naranja. El clásico de brunch, mitad y mitad.',
    perfiles: ['frutal', 'refrescante', 'dulce'],
    intensidad: 1,
    base: 'espumante',
    sinAlcohol: false,
    vaso: 'Copa de champán',
    minutos: 2,
    origen: 'Francia',
    ingredientes: [
      { rol: 'espumante', medida: '75 ml bien frío' },
      { rol: 'jugo-naranja', medida: '75 ml bien frío' },
    ],
    pasos: [
      'Sirve el jugo de naranja en la copa.',
      'Completa con el espumante, despacio para no perder gas.',
      'No revuelvas: el gas se pierde si mueves mucho la copa.',
    ],
    tip: 'Mitad y mitad es la proporción clásica; con más espumante queda más seco y menos dulce.',
  },
  {
    id: 'black-russian',
    nombre: 'Black russian',
    resumen: 'Vodka con licor de café. Dos ingredientes, cero adornos.',
    perfiles: ['fuerte', 'dulce', 'cremoso'],
    intensidad: 3,
    base: 'vodka',
    sinAlcohol: false,
    vaso: 'Vaso bajo',
    minutos: 2,
    origen: 'Bélgica',
    ingredientes: [
      { rol: 'vodka', medida: '50 ml' },
      { rol: 'licor-cafe', medida: '25 ml' },
      { casa: 'hielo', medida: '2 cubos grandes' },
    ],
    pasos: [
      'Pon los cubos de hielo en el vaso.',
      'Sirve el vodka y después el licor de café.',
      'Revuelve una vez, despacio.',
    ],
    tip: 'Con un chorro de crema o leche bien fría encima, esto se convierte en un White Russian.',
  },
  {
    id: 'mojito-sin-alcohol',
    nombre: 'Mojito sin alcohol',
    resumen: 'La misma menta y limón del mojito, sin el ron. Nadie nota la diferencia hasta el final.',
    perfiles: ['refrescante', 'citrico', 'dulce'],
    intensidad: 1,
    base: null,
    sinAlcohol: true,
    vaso: 'Vaso largo',
    minutos: 4,
    origen: 'Cuba',
    ingredientes: [
      { casa: 'menta', medida: '10 hojas' },
      { casa: 'limon', medida: '25 ml de jugo' },
      { casa: 'azucar', medida: '2 cucharaditas' },
      { rol: 'agua-con-gas', medida: '150 ml' },
      { casa: 'hielo', medida: 'hielo molido' },
    ],
    pasos: [
      'Aprieta la menta contra la palma de la mano y suéltala en el vaso. No la muelas.',
      'Suma azúcar y jugo de limón, revuelve hasta disolver.',
      'Llena de hielo molido y completa con agua con gas.',
    ],
    tip: 'Si te gusta más dulce, sube el azúcar antes de llegar al hielo: después cuesta que se disuelva.',
  },
  {
    id: 'mula-sin-alcohol',
    nombre: 'Mula sin alcohol',
    resumen: 'Jengibre y limón, la parte que más se nota del moscow mule, sin el vodka.',
    perfiles: ['especiado', 'refrescante', 'citrico'],
    intensidad: 1,
    base: null,
    sinAlcohol: true,
    vaso: 'Jarro de cobre o vaso largo',
    minutos: 3,
    origen: 'Estados Unidos',
    ingredientes: [
      { rol: 'ginger-beer', medida: '200 ml' },
      { casa: 'limon', medida: '15 ml de jugo' },
      { casa: 'hielo', medida: 'vaso lleno' },
    ],
    pasos: [
      'Exprime el limón directo en el vaso.',
      'Llena de hielo.',
      'Completa con ginger beer bien fría y revuelve una vez.',
    ],
    tip: 'Con ginger ale en vez de ginger beer queda más dulce y menos picante.',
  },
  {
    id: 'cooler-pepino-menta',
    nombre: 'Cooler de pepino y menta',
    resumen: 'Fresco como agua de spa, pero con burbuja. El más liviano de la carta.',
    perfiles: ['refrescante', 'citrico'],
    intensidad: 1,
    base: null,
    sinAlcohol: true,
    vaso: 'Vaso largo',
    minutos: 4,
    origen: 'Chile',
    ingredientes: [
      { casa: 'pepino', medida: '4 rodajas' },
      { casa: 'menta', medida: '6 hojas' },
      { casa: 'limon', medida: '15 ml de jugo' },
      { rol: 'agua-con-gas', medida: '150 ml' },
      { casa: 'hielo', medida: 'vaso lleno' },
    ],
    pasos: [
      'Machaca suave el pepino y la menta en el fondo del vaso.',
      'Suma el jugo de limón y llena de hielo.',
      'Completa con agua con gas.',
    ],
    tip: 'El pepino sin pelar aporta más color verde al vaso; pelado queda más neutro.',
  },
  {
    id: 'cooler-frutilla-naranja',
    nombre: 'Cooler de frutilla y naranja',
    resumen: 'Frutal y con burbuja. El favorito de quien no toma pero quiere algo especial.',
    perfiles: ['frutal', 'dulce', 'refrescante'],
    intensidad: 1,
    base: null,
    sinAlcohol: true,
    vaso: 'Vaso largo',
    minutos: 3,
    origen: 'Chile',
    ingredientes: [
      { rol: 'jugo-frutilla', medida: '60 ml' },
      { rol: 'jugo-naranja', medida: '90 ml' },
      { rol: 'agua-con-gas', medida: '60 ml' },
      { casa: 'hielo', medida: 'vaso lleno' },
    ],
    pasos: [
      'Llena el vaso de hielo.',
      'Sirve los dos jugos y revuelve.',
      'Completa con agua con gas justo antes de tomar.',
    ],
    tip: 'Sirve los jugos bien fríos: si están tibios, el hielo se derrite antes de que agarre gas.',
  },
  {
    id: 'cafe-helado',
    nombre: 'Café helado dulce',
    resumen: 'Espresso frío con un toque de dulzor. Para el que necesita cafeína, no alcohol.',
    perfiles: ['dulce', 'cremoso'],
    intensidad: 1,
    base: null,
    sinAlcohol: true,
    vaso: 'Vaso bajo',
    minutos: 4,
    origen: 'Chile',
    ingredientes: [
      { casa: 'cafe', medida: '90 ml de espresso, frío' },
      { rol: 'jarabe-goma', medida: '15 ml' },
      { casa: 'hielo', medida: 'vaso lleno' },
    ],
    pasos: [
      'Prepara el espresso y déjalo enfriar a temperatura ambiente antes de usarlo.',
      'Llena el vaso de hielo y sirve el café encima.',
      'Agrega el jarabe de goma y revuelve.',
    ],
    tip: 'Nunca sirvas el espresso caliente sobre el hielo: se derrite todo y queda aguado.',
  },
]
